### ISSUE TITLE
Normalize keeps `---` but removes `...` for yml files

### ISSUE THREAD

**Issue by yorsant** [glebm/i18n-tasks#419] opened 2022-02-24 22:38 UTC
I have noticed that normalizing files removes the three dots (`...`) at the end of every file.
Is it possible to keep them?

**Comment by yorsant** [comment] 2022-02-24 22:55
```ruby
irb(main):003:0> YAML.dump("hey")
=> "--- hey\n"
```

This may be the reason why.

I think it used to be like (based on doc page):
```ruby
# Emit some YAML
YAML.dump("foo")     # => "--- foo\n...\n"
```

**Comment by davidwessman** [comment] 2022-04-03 08:07
Hello @yorsant 

- Can you check which implementation you are using for `YAML`?
  E.g. in my Rails app it looks like:
  ```ruby
  irb(main):001:0> YAML
  => Psych
  ```
  
- Can you check which version of `libyaml` you are using?
  ```ruby
  irb(main):002:0> YAML.libyaml_version
  => [0, 2, 5]
  ```
  
I think these issues might be similar:
https://github.com/yaml/libyaml/issues/46
https://github.com/Locale/localeapp/issues/178

Can you try to update to libyaml 0.2.5 or later and then reinstall your rubies and see if it helps?

**Comment by davidwessman** [comment] 2022-04-03 08:48
Possible duplicate of #355

**Comment by yorsant** [comment] 2022-04-08 14:06
@davidwessman I'm using an old version of `YAML.libyaml_version`. Thanks, I'll check if updating solves the issue.

**Comment by davidwessman** [comment] 2022-05-15 12:40
@yorsant Can we close this issue?

**Closed** 2022-05-16 20:06 UTC
