### ISSUE TITLE
No detecting use of locale keys on form helpers

### ISSUE THREAD

**Issue by fguillen** [glebm/i18n-tasks#554] opened 2024-03-29 14:32 UTC
The use of the locale key `activerecord.attributes.user.password`  is not detected even if it is used in a form helper like:

```
<%= f.label :password %>
```

Is this expected? is it a limitation of the library? or is a bug or something I am doing wrong?

**Comment by davidwessman** [comment] 2024-04-03 18:36
There are no matchers for this case unfortunately. You can take inspiration from the different matchers we have added for model attributes and email subjects.

**Comment by fguillen** [comment] 2024-04-04 16:45
Hi @davidwessman thanks for checking it out. I assume you mean [this example matcher](https://github.com/glebm/i18n-tasks/blob/main/lib/i18n/tasks/scanners/ast_matchers/rails_model_matcher.rb). 

I confess it looks like it would be a nightmare to try to infer what model is being used in a `f.label` tag. I assume we should have to parse all `.erb` looking for the proper model for the form. Not talking when the `f.label` is in a partial not including the parent `form`. 

Do you have any idea if this can be achievable for the task `i18n-tasks missing`?

**Comment by davidwessman** [comment] 2024-05-10 05:43
Yeah, or add some magic comment for the form-model or something like that.

**Comment by davidwessman** [comment] 2024-10-20 13:34
Since this is not a bug, but a known limitation I will close this for now.

**Closed by davidwessman** 2024-10-20 13:34 UTC

**Comment by glebm** [comment] 2024-10-20 20:30
Yeah, as it can be difficult even for a human to infer the right key name, magic comments or even simply calling `t` explicitly is probably the best solution here.
