### ISSUE TITLE
better_html scans any project that uses i18n-tasks

### ISSUE THREAD

**Issue by eligordon** [glebm/i18n-tasks#422] opened 2022-03-23 16:35 UTC
With v1.0.0 of `i18n-tasks` included in my project, `better_html` is now scanning (and occasionally criticizing the HTML markup of) the files in my project and any other gems that I use on render. I doubt this is the effect you wanted. Perhaps you only need to `require 'better_html/parser'`?

(@davidwessman)

**Comment by davidwessman** [comment] 2022-03-23 18:14
@eligordon Can you elaborate on how to reproduce it?
Please include:
- What you define in your Gemfile (do you use better_html already?)
- What command you are running?

I did a pr on #423 that might fix it.

**Comment by jsantos** [comment] 2022-03-24 02:13
Bumped into this after upgrading to 1.0.0. I didn't used better_html before the upgrade, so now it breaks the dev environment (at least) just because of some double quotes are used to define conditional classes. Will rollback until #423 is merged :) Thanks for all your work!

**Comment by davidwessman** [comment] 2022-03-24 08:01
How do you use `i18n-tasks`? Are you importing it to create a test / spec?
I cannot reproduce it on locally :/

**Closed** 2022-03-24 09:02 UTC

**Comment by pavel-workpath** [comment] 2022-03-24 09:16
We are having a similar issue in our specs on 1.0.0

We basically use a copy of [the template spec](https://github.com/glebm/i18n-tasks/blob/main/templates/rspec/i18n_spec.rb), and it seems that after that every template we render during testing get validated by `better_html`. Which is unexpected

Thanks for checking it and looking forward to that 1.0.1!

**Comment by glebm** [comment] 2022-03-24 09:18
I released 1.0.1 a few minutes ago!

**Comment by davidwessman** [comment] 2022-03-24 09:24
> We are having a similar issue in our specs on 1.0.0
> 
> 
> 
> We basically use a copy of [the template spec](https://github.com/glebm/i18n-tasks/blob/main/templates/rspec/i18n_spec.rb), and it seems that after that every template we render during testing get validated by `better_html`. Which is unexpected
> 
> 
> 
> Thanks for checking it and looking forward to that 1.0.1!

Ah, I will see if I can write a spec for this. Can you try 1.0.1?

**Comment by pavel-workpath** [comment] 2022-03-24 09:34
Thanks guys! The 1.0.1 looks fine, both specs and tasks work as they did before the update
